webtalk_init -webtalk_dir C:/Users/kari_/Desktop/ECE 369A/369A_lab/LabProject/LabProject.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 20 12:38:38 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "11746163-20f9-46ca-953e-b7d94f8b5b67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "717b3cd805704090b9da4dfab5b6ba2b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "72" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-1355U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2611 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7652_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2474635334 -regid "" -xml C:/Users/kari_/Desktop/ECE 369A/369A_lab/LabProject/LabProject.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/kari_/Desktop/ECE 369A/369A_lab/LabProject/LabProject.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/kari_/Desktop/ECE 369A/369A_lab/LabProject/LabProject.sim/sim_1/behav/xsim/xsim.dir/top_level_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
